### ISSUE TITLE
Hello, Running the code has a Error

### ISSUE THREAD

**Issue by HairMoke** [nik-sm/thu-rsvp-dataset#2]
Error:
2024-10-14 09:21:37.856 | INFO     | thu_rsvp_dataset.thu:get_data:87 - Check download...
Download + Verify Files:   0%|          | 0/11 [00:00<?, ?it/s]2024-10-14 09:21:37.865 | INFO     | thu_rsvp_dataset.thu:_check_download:105 - Already have C:\Users\ybac2\Desktop\thu-rsvp-dataset\datasets\thu\64-channels.loc, verified checksum: True 
2024-10-14 09:21:37.870 | INFO     | thu_rsvp_dataset.thu:_check_download:105 - Already have C:\Users\ybac2\Desktop\thu-rsvp-dataset\datasets\thu\note.txt, verified checksum: True 

Readme.txt (0.00 GB): 0.00B [00:00, ?B/s]
Download + Verify Files:  18%|█▊        | 2/11 [00:02<00:12,  1.42s/it]
Traceback (most recent call last):
  File "C:\Users\ybac2\Desktop\thu-rsvp-dataset\examples\load_dataset.py", line 36, in <module>
    data, labels, subj_id, sess_id = thu_rsvp.get_data()
  File "C:\Users\ybac2\Desktop\thu-rsvp-dataset\thu_rsvp_dataset\thu.py", line 88, in get_data
    self._check_download()
  File "C:\Users\ybac2\Desktop\thu-rsvp-dataset\thu_rsvp_dataset\thu.py", line 112, in _check_download
    raise ValueError(f"md5sum mismatch for: {basename}")
ValueError: md5sum mismatch for: Readme.txt

**Comment by nik-sm** [comment]
Hi - Based on the error, the contents of `Readme.txt` on your local machine don't match what was expected. Can you try `cat Readme.txt` for the local file you received? 

- If it looks like a valid and fully-formed file, then it's possible that the authors of this dataset have modified its contents since when I recorded the checksums. (Note that I didn't create the dataset and can't control its contents)
- If your local file looks malformed, it could be that your connection dropped partway through download.

In either case, if you want to try loading the dataset anyway, you can remove any partially downloaded files (or remove the whole folder), and rerun but set the argument `verify_sha256=False`. That way, if the contents of the file have changed but the contents are still valid and useful, you can proceed with your downstream tasks

(Apologies that the error mentions "md5" while the argument mentions "sha256" - looks like I changed my mind about which hash algorithm to use during development and forgot to rename things)

**Comment by HairMoke** [comment]
Thank you for your response, and I have resolved ths issue with your help .Wish everything goes well with your work!

嘿呦喂
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "nik-sm/thu-rsvp-dataset"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月15日(星期二) 上午6:04
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [nik-sm/thu-rsvp-dataset] Hello, Running the code has a Error (Issue #2)





 
Hi - Based on the error, the contents of Readme.txt on your local machine don't match what was expected. Can you try cat Readme.txt for the local file you received?
  
If it looks like a valid and fully-formed file, then it's possible that the authors of this dataset have modified its contents since when I recorded the checksums. (Note that I didn't create the dataset and can't control its contents)
 
If your local file looks malformed, it could be that your connection dropped partway through download.
  
In either case, if you want to try loading the dataset anyway, you can remove any partially downloaded files (or remove the whole folder), and rerun but set the argument verify_sha256=False. That way, if the contents of the file have changed but the contents are still valid and useful, you can proceed with your downstream tasks
 
(Apologies that the error mentions "md5" while the argument mentions "sha256" - looks like I changed my mind about which hash algorithm to use during development and forgot to rename things)
